### ISSUE TITLE
API Docs link broken

### ISSUE THREAD

**Issue by Jossec101** [navikt/arxaas#142]
Hi all,

As of today, the link for the API DOCs is broken: https://navikt.github.io/ARXaaS/

Best regards

**Comment by sonhal** [comment]
Hi @Jossec101, we will look into fixing it asap. Thank you for letting us know!
If you need the docs asap its possible to generate the API docs locally by cloning the repo and building the project. The docs will be located in the target folder.

Best regards,
Sondre

**Comment by sonhal** [comment]
Broken link has been fixed. Closing the issue.
